CREATE TABLE users
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
login VARCHAR(45) NOT NULL,
password VARCHAR(200) NOT NULL,
mail VARCHAR(45) NOT NULL,
salt INT NOT NULL,
is_admin BOOLEAN NOT NULL
);


CREATE TABLE book
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
year INT NOT NULL,
genre VARCHAR(45) NOT NULL,
description VARCHAR(1500) NOT NULL,
link VARCHAR(300) NOT NULL,
author VARCHAR(150) NOT NULL
);

CREATE TABLE comments
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
comment VARCHAR(500) NOT NULL,
author_id INT NOT NULL,
book_id INT NOT NULL,
FOREIGN KEY (book_id) REFERENCES book(id),
FOREIGN KEY (author_id) REFERENCES users(id)
);

ALTER TABLE book ADD FULLTEXT (name, description, genre, author);
